#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html

#SBATCH --nodes=1
##SBATCH -n 12
#SBATCH --ntasks-per-node=6
#SBATCH --account=hagan-lab
#SBATCH --partition=hagan-gpu
#SBATCH --qos=medium
#SBATCH --nodelist=gpu-l40-4-1
#SBATCH --gres=gpu:L40
##SBATCH --gres=gpu:RTX2:1
#SBATCH --time=3-00:00:00
##SBATCH --exclusive 
# export NCCL_DEBUG=INFO


# OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread


module load cuda/12.4
module load share_modules/FFTW/3.3.8_gcc_sp

#nvcc pid_solver_3.cpp -LcuPSS/src/ -lcufft -lfftw3f -lcurand -lcupss -O2 -o pid
#run the application:
# applications may perform better with --gpu-bind=none instead of --gpu-bind=single:1

srun -n 1 -c 4 --cpu_bind=cores --gpu-bind=none ./pid ${1} ${2} ${3}
